### ISSUE TITLE
Component updates break existing configs

### ISSUE THREAD

**Issue by miguelangel-nubla** [PedroKTFC/esphome-tesla-ble#95]
I don't know if you know about the following since it is in dev:

If I upgrade the device from `esphome-tesla-ble/dev`, it sucessfully compiles and works for a minute but then the device crashes and reboots without a helpful log message.

The culprit seems changes like `https://github.com/PedroKTFC/esphome-tesla-ble/commit/8341a6f0417ef0692e474abde30032882d804976` in the config for the component, and me not updating the [client.yml](https://github.com/PedroKTFC/esphome-tesla-ble/blob/newteslalib/packages/client.yml) with the new sensors added.

I believe the internal component code just tries to write the state to those missing sensors and crashes.

This should not happen because the user is expected to only include yaml config for the sensors needed.
The component should check if the sensor is configured before trying to write to it.

**Comment by top-gun** [comment]
I think your approach is a bit off the standard. Most people use the example-yaml and that will load the latest client.yml from Github, so they have all the needed entities. Why would you not want the new entities, if I may ask? If you feel you don't need them, you can simply deactivate them and stay compatible with the standard codebase.

**Comment by miguelangel-nubla** [comment]
I do want them, but that is beyond the point.
This is just how esphome components work, not a quirk of my approach.

Either the option (entity config) is mandatory, in which case a compilation error must be thrown,
Or it is *not* mandatory, in which case it should work fine without it.

Currently the behavior does not fit either.

I am just raising this up as I don't know if PedroKTFC is aware of this, and may be interested in incorporating this information to the development decisions.

**Comment by top-gun** [comment]
> I do want them, but that is beyond the point. This is just how esphome components work, not a quirk of my approach.
> 
> Either the option (entity config) is mandatory, in which case a compilation error must be thrown and compilation not succeed Or it is _not_ mandatory, in which case it should work fine without it.
> 
> Currently the behavior does not fit either.
> 
> I am just raising this up as I don't know if PedroKTFC is aware of this, and may be interested in incorporating this information to the development decisions.

Actually, if you use his example, the latest client.yaml is automatically applied and all new entities are automatically applied.

**Comment by top-gun** [comment]
I commend you on your level of experience. Personally, I will continue to benefit from automatic configuration and wish you all the best.

**Comment by mr-p666** [comment]
It seems, that there was a problem with esphome 2025.7.1 because after updating to 2025.7.2 the problem is vanished. Also a look into the changelog suggests, that the cause was there:

Fix AsyncTCP version mismatch between platformio.ini and async_tcp component [esphome#9676](https://github.com/esphome/esphome/pull/9676) by [@bdraco](https://github.com/bdraco)

**Comment by PedroKTFC** [comment]
I will look at this at some point but I confess it will be a lower priority at the moment, especially as my home broadband is currently down so I'm very limited what I can do. My immediate thoughts, without any further analysis, is that it would be a real pain in the code to check if a sensor exists so I'm likely to want to make it a compilation requirement.

**Comment by PedroKTFC** [comment]
That's a decent point and I'll look at it. I'll try with and without before releasing anything. As you say, in a stable environment it would seem unnecessary if it's wasteful. Indeed, I've never used it.
