### ISSUE TITLE
Missing files when updating to Esphome 2025.8.0

### ISSUE THREAD

**Issue by cybuletz** [PedroKTFC/esphome-tesla-ble#130]
Hi,

After updating ESPHome to 2025.8.0 I can no longer use the current configuration as I am getting some errors:

```
Compiling .pioenvs/tesla-ble/src/esphome/components/tesla_ble_vehicle/log.cpp.o
src/esphome/components/tesla_ble_vehicle/log.cpp:7:10: fatal error: car_server.pb.h: No such file or directory

*****************************************************************************
* Looking for car_server.pb.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:car_server.pb.h"
* Web  > https://registry.platformio.org/search?q=header:%1B%5Bm%1B%5BKcar_server.pb.h
*
*****************************************************************************

    7 | #include <car_server.pb.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/tesla-ble/src/esphome/components/tesla_ble_vehicle/log.cpp.o] Error 1
========================= [FAILED] Took 140.28 seconds =========================

```

**This is my current Yaml:**

```
substitutions:
  friendly_name: TeslaBLE
  device_name: tesla-ble
  device_description: Tesla BLE
  ble_mac_address: !secret ble_mac_address
  tesla_vin: !secret tesla_vin

api:
  encryption:
    key: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#external_components:
#  - components: [tesla_ble_vehicle]
#    source: github://PedroKTFC/esphome-tesla-ble@dev

external_components:
  source: github://PedroKTFC/esphome-tesla-ble

packages:
  common: github://PedroKTFC/esphome-tesla-ble/packages/common.yml
  client: github://PedroKTFC/esphome-tesla-ble/packages/client.yml

esphome:
  name: ${device_name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}


esp32:
  board: esp32dev
  framework:
    type: esp-idf

ota:
  - platform: esphome
    password: ""

logger:
  baud_rate: 0


```

**Comment by cybuletz** [comment]
this is weird:
previously, I had library defined as well as the commented external_components section from above.

I have readded the libraries, left the external_components commented and it worked.

In any case, thanks for the help!
